"use client";
import { FormEvent, useEffect, useId, useState } from "react";
const items = [["Mortgage Affordability Calculator","Calculator","/calculators"],["Mortgage Repayment Calculator","Calculator","/calculators"],["Stamp Duty Calculator","Calculator","/calculators"],["Life Insurance Calculator","Calculator","/calculators"],["First Time Buyer Guide","Guide","/guides"],["Remortgaging Explained","Guide","/guides"],["Income Protection Guide","Guide","/guides"],["Mortgage & Protection","Category","/mortgage-protection"],["Latest mortgage articles","Blog","/blogs"]];
export function SearchAndAdvice() {
 const [search,setSearch]=useState(false),[advice,setAdvice]=useState(false),[query,setQuery]=useState(""); const titleId=useId();
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape"){setSearch(false);setAdvice(false)}if((e.metaKey||e.ctrlKey)&&e.key==="k"){e.preventDefault();setSearch(true)}};addEventListener("keydown",close);return()=>removeEventListener("keydown",close)},[]);
 const results=items.filter(([name,type])=>`${name} ${type}`.toLowerCase().includes(query.toLowerCase()));
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const body=["Nikera Hub advice request","",`Full name: ${d.get("name")}`,`Email: ${d.get("email")}`,`Phone: ${d.get("phone")}`,`Preferred contact time: ${d.get("time")}`,`Additional notes: ${d.get("notes")}`,"",`Timestamp: ${new Date().toISOString()}`,`Source page: ${location.href}`].join("\n");location.href=`mailto:hello@nikera.co.uk?subject=${encodeURIComponent("Nikera Hub professional advice request")}&body=${encodeURIComponent(body)}`}
 return <><button className="search-trigger" onClick={()=>setSearch(true)} aria-label="Search Hub"><span>⌕</span> Search <kbd>⌘ K</kbd></button><button className="floating-advice" onClick={()=>setAdvice(true)}><span>↗</span><b>Need Mortgage Advice?</b></button>
 {search&&<div className="modal-backdrop" onMouseDown={()=>setSearch(false)}><section className="search-modal" role="dialog" aria-modal="true" aria-label="Search Hub" onMouseDown={e=>e.stopPropagation()}><div className="search-input"><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search calculators, guides, blogs…"/><button onClick={()=>setSearch(false)}>ESC</button></div><div className="search-results">{results.map(([name,type,url])=><a href={url} key={name}><span>{type}</span><b>{name}</b><i>→</i></a>)}{!results.length&&<p>No results found. Try another search.</p>}</div></section></div>}
 {advice&&<div className="modal-backdrop" onMouseDown={()=>setAdvice(false)}><section className="advice-modal" role="dialog" aria-modal="true" aria-labelledby={titleId} onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setAdvice(false)} aria-label="Close">×</button><span className="kicker">PROFESSIONAL GUIDANCE</span><h2 id={titleId}>Request mortgage advice</h2><p>A trusted mortgage adviser can review your needs and discuss the options available.</p><form onSubmit={submit}><label>Full name<input name="name" required autoComplete="name"/></label><label>Email<input name="email" required type="email" autoComplete="email"/></label><label>Phone number<input name="phone" required type="tel" autoComplete="tel"/></label><label>Preferred contact time<select name="time"><option>Morning</option><option>Afternoon</option><option>Evening</option></select></label><label className="full">Additional notes<textarea name="notes" rows={3}/></label><button className="full" type="submit">Request Professional Advice →</button></form><small>Submitting opens your email app with the enquiry prepared for hello@nikera.co.uk.</small></section></div>}</>;
}
